name: Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Execute py script
        uses: azureswastika/blog.py@v1
      
      - name: Ls
        run: |
          pip freeze
          ls
          ls /blog
