name: Hello World action

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Run
        run: |
          git clone https://github.com/azureswastika/blog.py.git
          ls
          pip install -r blog.py/requirements.txt
          python blog.py/main.py
          ls blog.py/
          ls blog.py/blog
