name: Hello World action

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
     DOCKER_IMAGE: azureswastika/blog.py

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Build Docker
        run: |
          $(which docker) build --tag ${DOCKER_IMAGE}:latest .
          ls
